model_and_diffusion:
  model_path: /disk4/royha/ilvr/models/ffhq_10m.pt
  image_size: 256
  num_channels: 128
  num_res_blocks: 1
  num_heads: 4
  num_heads_upsample: -1
  num_head_channels: 64
  attention_resolutions: '16'
  channel_mult: ''
  dropout: 0.0
  class_cond: false
  use_checkpoint: false
  use_scale_shift_norm: true
  resblock_updown: true
  use_fp16: false
  use_new_attention_order: false
  learn_sigma: true
  diffusion_steps: 1000
  noise_schedule: linear
  timestep_respacing: ''
  use_kl: false
  predict_xstart: false
  rescale_timesteps: false
  rescale_learned_sigmas: false
